flix/pragstudio-rails-code/example-app/16-layouts/events/config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  resources :events
end

flix/pragstudio-rails-code/example-app/16-layouts/events/app/models/event.rb
class Event < ApplicationRecord
  def self.upcoming
    where('starts_at >= ?', Time.now).order(:starts_at)
  end

  def free?
    price.blank? || price.zero?
  end
end

flix/pragstudio-rails-code/example-app/16-layouts/events/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to @event
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to @event
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

private

  def event_params
    params.require(:event).
      permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
  end

end

flix/pragstudio-rails-code/example-app/16-layouts/events/app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, "Free")
    else
      number_to_currency(event.price)
    end
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'placeholder.png'
    else
      image_tag event.image_file_name
    end
  end
end

flix/pragstudio-rails-code/example-app/16-layouts/events/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name, autofocus: true %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols: 40, rows: 7 %>
  </p>
  <p>
    <%= f.label :location %><br/>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :price %><br/>
    <%= f.number_field :price, size: 6 %>
  </p>
  <p>
    <%= f.label :starts_at %><br/>
    <%= f.datetime_select :starts_at %>
  </p>
  <p>
    <%= f.label :image_file_name %><br/>
    <%= f.text_field :image_file_name, size: 30, 
           placeholder: "GIF, JPG, or PNG file name" %>
  </p>
  <p>
    <%= f.label :capacity %><br/>
    <%= f.number_field :capacity %>
  </p>
  <p>
    <%= f.submit %> |
    <%= link_to "Cancel", events_path %>
  </p>
<% end %>

flix/pragstudio-rails-code/example-app/16-layouts/events/app/views/events/edit.html.erb
<header>
  <h1>Edit: <%= @event.name %></h1>
</header>

<%= render 'form' %>

flix/pragstudio-rails-code/example-app/16-layouts/events/app/views/events/index.html.erb
<h1><%= pluralize(@events.size, 'Event') %></h1>

<% @events.each do |event| %>
  <article>
    <header>
      <%= image_for(event) %>  
      <h2><%= link_to event.name, event_url(event) %></h2>
      <h3><%= pluralize(event.capacity, 'spot') %></h3>
    </header>
    <p>
      <%= truncate(event.description, length: 35, separator: ' ') %>
    </p>
    <table>
      <tr>
        <th>When:</th>
        <td><%= event.starts_at %></td>
      </tr>
      <tr>
        <th>Where:</th>
        <td><%= event.location %></td>
      </tr>
      <tr>
        <th>Price:</th>
        <td><%= format_price(event) %></td>
      </tr>
    </table>
  </article>
<% end %>

flix/pragstudio-rails-code/example-app/16-layouts/events/app/views/events/new.html.erb
<header>
  <h1>Create Event</h1>
</header>

<%= render 'form' %>

flix/pragstudio-rails-code/example-app/16-layouts/events/app/views/events/show.html.erb
<article>
  <header>
    <%= image_for(@event) %>
    <h1><%= @event.name %></h1>
  </header>
  <p>
    <%= @event.description %>
  </p>
  <h3>When</h3>
  <p>
    <%= @event.starts_at %>
  </p>
  <h3>Where</h3>
  <p>
    <%= @event.location %>
  </p>
  <h3>Price</h3>
  <p>
    <%= format_price(@event) %>
  </p>
  <h3>Capacity</h3>
  <p>
    <%= pluralize(@event.capacity, 'spot') %>
  </p>
</article>

<nav>
  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Delete', event_path(@event), 
                   method: :delete,  
                   data: { confirm: 'Are you sure?' } %>
</nav>